#!/usr/bin/python3

import glob
import os

from tools import data_util, generate_full_data

SELF_DIR = os.path.dirname(os.path.realpath(__file__))

def clean():
    for daily in glob.glob("d/*.json"):
        os.remove(daily)
    for country in glob.glob("c/*.json"):
        os.remove(country)

def update():
    generate_full_data.generate_data(
        os.path.join(SELF_DIR, "d"),
        os.path.join(SELF_DIR, "c"),
        overwrite=True, quiet=False)
    data_util.retrieve_generable_data(".", should_overwrite=True, quiet=False)
    # Note sure why there are two lines merged together
    os.system("sed -i 's/GB32/GB\\n32/' location_info.data")

if __name__ == "__main__":
    clean()
    update()
