#!/usr/bin/python3

import glob
import os
import sys

SELF_DIR = os.path.dirname(os.path.realpath(__file__))

def check_for_common_repo():
    if not os.path.exists("../common"):
        print("Please clone the 'common' repo as a sibling of this one:")
        print("cd .. && git clone git@github.com:globaldothealth/common.git")
        return False
    return True

def clean():
    for daily in glob.glob("d/*.json"):
        os.remove(daily)
    for country in glob.glob("c/*.json"):
        os.remove(country)

def update():
    generate_full_data.generate_data(
        os.path.join(SELF_DIR, "d"),
        os.path.join(SELF_DIR, "c"),
        overwrite=True, quiet=False)
    data_util.retrieve_generable_data(".", should_overwrite=True, quiet=False)
    # Note sure why there are two lines merged together for a couple of locations
    os.system("sed -i 's/GB32/GB\\n32/' location_info.data")
    os.system("sed -i 's/PE32/PE\\n32/' location_info.data")
    os.system("sed -i 's/PE18/PE\\n18/' location_info.data")
    os.system("./sanitize_location_info")
    # Add any new daily file.
    os.system("git add d/*.json")

if __name__ == "__main__":
    if check_for_common_repo():
        sys.path.insert(0, "../common/tools")
        from tools import data_util, generate_full_data
        clean()
        update()
